"""initial schema

Revision ID: 20260728_0001
Revises:
Create Date: 2026-07-28 15:29:30.690777
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260728_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_table(
        "cluster_runs",
        sa.Column("cluster_run_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("embedding_type", sa.String(length=64), nullable=False),
        sa.Column("input_embedding_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("preprocessing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cluster_count", sa.Integer(), nullable=True),
        sa.Column("noise_count", sa.Integer(), nullable=True),
        sa.Column("noise_ratio", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cluster_run_id"),
    )
    op.create_index(
        op.f("ix_cluster_runs_embedding_type"), "cluster_runs", ["embedding_type"], unique=False
    )
    op.create_index(op.f("ix_cluster_runs_status"), "cluster_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_cluster_runs_workspace_id"), "cluster_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "source_files",
        sa.Column("source_file_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("original_file_name", sa.String(length=1024), nullable=False),
        sa.Column("file_type", sa.String(length=32), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("file_tree_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_file_id"),
        sa.UniqueConstraint("workspace_id", "sha256", name="uq_source_file_workspace_sha256"),
    )
    op.create_index(
        op.f("ix_source_files_processing_status"),
        "source_files",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_files_workspace_id"), "source_files", ["workspace_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("source_file_id", sa.String(length=64), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("file_name", sa.String(length=1024), nullable=False),
        sa.Column("asset_name", sa.String(length=1024), nullable=True),
        sa.Column("asset_description", sa.Text(), nullable=True),
        sa.Column("asset_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_contexts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("derived_file_uri", sa.Text(), nullable=True),
        sa.Column("preview_uri", sa.Text(), nullable=True),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("feature_revision", sa.Integer(), nullable=False),
        sa.Column("embedding_revision", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"], ["source_files.source_file_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(op.f("ix_assets_asset_type"), "assets", ["asset_type"], unique=False)
    op.create_index(
        op.f("ix_assets_processing_status"), "assets", ["processing_status"], unique=False
    )
    op.create_index(op.f("ix_assets_source_file_id"), "assets", ["source_file_id"], unique=False)
    op.create_index(op.f("ix_assets_workspace_id"), "assets", ["workspace_id"], unique=False)
    op.create_table(
        "cluster_capsules",
        sa.Column("cluster_capsule_id", sa.String(length=64), nullable=False),
        sa.Column("cluster_run_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("embedding_type", sa.String(length=64), nullable=False),
        sa.Column("cluster_label", sa.Integer(), nullable=False),
        sa.Column("effective_name", sa.String(length=1024), nullable=False),
        sa.Column("effective_description", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("average_membership_probability", sa.Float(), nullable=False),
        sa.Column(
            "representative_asset_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_run_id"], ["cluster_runs.cluster_run_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cluster_capsule_id"),
        sa.UniqueConstraint("cluster_run_id", "cluster_label", name="uq_cluster_capsule_run_label"),
    )
    op.create_index(
        op.f("ix_cluster_capsules_cluster_run_id"),
        "cluster_capsules",
        ["cluster_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cluster_capsules_workspace_id"), "cluster_capsules", ["workspace_id"], unique=False
    )
    op.create_table(
        "cluster_memberships",
        sa.Column("membership_id", sa.String(length=64), nullable=False),
        sa.Column("cluster_run_id", sa.String(length=64), nullable=False),
        sa.Column("cluster_capsule_id", sa.String(length=64), nullable=True),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("hdbscan_label", sa.Integer(), nullable=False),
        sa.Column("membership_probability", sa.Float(), nullable=False),
        sa.Column("is_noise", sa.Boolean(), nullable=False),
        sa.Column("distance_to_representative", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["cluster_capsule_id"], ["cluster_capsules.cluster_capsule_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["cluster_run_id"], ["cluster_runs.cluster_run_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("membership_id"),
        sa.UniqueConstraint("cluster_run_id", "asset_id", name="uq_cluster_membership_run_asset"),
    )
    op.create_index(
        op.f("ix_cluster_memberships_asset_id"), "cluster_memberships", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_cluster_memberships_cluster_capsule_id"),
        "cluster_memberships",
        ["cluster_capsule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cluster_memberships_cluster_run_id"),
        "cluster_memberships",
        ["cluster_run_id"],
        unique=False,
    )
    op.create_table(
        "embedding_records",
        sa.Column("embedding_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("embedding_type", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("source_content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_source_mode", sa.String(length=64), nullable=False),
        sa.Column("milvus_collection", sa.String(length=255), nullable=False),
        sa.Column("milvus_primary_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("embedding_id"),
        sa.UniqueConstraint(
            "asset_id",
            "embedding_type",
            "model_name",
            "dimension",
            "source_content_hash",
            name="uq_embedding_logical_input",
        ),
        sa.UniqueConstraint("milvus_primary_key"),
    )
    op.create_index(
        op.f("ix_embedding_records_asset_id"), "embedding_records", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_embedding_records_embedding_type"),
        "embedding_records",
        ["embedding_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_embedding_records_status"), "embedding_records", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_embedding_records_workspace_id"),
        "embedding_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "model_call_logs",
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("call_id"),
        sa.UniqueConstraint(
            "asset_id", "operation", "model_name", "input_hash", name="uq_model_call_logical_input"
        ),
    )
    op.create_index(
        op.f("ix_model_call_logs_asset_id"), "model_call_logs", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_model_call_logs_status"), "model_call_logs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_call_logs_status"), table_name="model_call_logs")
    op.drop_index(op.f("ix_model_call_logs_asset_id"), table_name="model_call_logs")
    op.drop_table("model_call_logs")
    op.drop_index(op.f("ix_embedding_records_workspace_id"), table_name="embedding_records")
    op.drop_index(op.f("ix_embedding_records_status"), table_name="embedding_records")
    op.drop_index(op.f("ix_embedding_records_embedding_type"), table_name="embedding_records")
    op.drop_index(op.f("ix_embedding_records_asset_id"), table_name="embedding_records")
    op.drop_table("embedding_records")
    op.drop_index(op.f("ix_cluster_memberships_cluster_run_id"), table_name="cluster_memberships")
    op.drop_index(
        op.f("ix_cluster_memberships_cluster_capsule_id"), table_name="cluster_memberships"
    )
    op.drop_index(op.f("ix_cluster_memberships_asset_id"), table_name="cluster_memberships")
    op.drop_table("cluster_memberships")
    op.drop_index(op.f("ix_cluster_capsules_workspace_id"), table_name="cluster_capsules")
    op.drop_index(op.f("ix_cluster_capsules_cluster_run_id"), table_name="cluster_capsules")
    op.drop_table("cluster_capsules")
    op.drop_index(op.f("ix_assets_workspace_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_source_file_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_processing_status"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_type"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_source_files_workspace_id"), table_name="source_files")
    op.drop_index(op.f("ix_source_files_processing_status"), table_name="source_files")
    op.drop_table("source_files")
    op.drop_index(op.f("ix_cluster_runs_workspace_id"), table_name="cluster_runs")
    op.drop_index(op.f("ix_cluster_runs_status"), table_name="cluster_runs")
    op.drop_index(op.f("ix_cluster_runs_embedding_type"), table_name="cluster_runs")
    op.drop_table("cluster_runs")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
